#!/bin/bash


_get_repolink () {
    local regex
    regex='(https?)://github.com/.+/.+'
    if [[ $KAAL_REPO == "KAALBOT" ]]
    then
        echo "aHR0cHM6Ly9naXRodWIuY29tL2thYWwwNDA4L0tBQUxCT1Q=" | base64 -d
    elif [[ $MAFIA_REPO == "KAALBOT" ]]
    then
        echo "aHR0cHM6Ly9naXRodWIuY29tL2thYWwwNDA4L0tBQUxCT1Q=" | base64 -d
    elif [[ $MAFIA_REPO =~ $regex ]]
    then
        if [[ $MAFIA_REPO_BRANCH ]]
        then
            echo "${KAAL_REPO}/archive/${KAAL_REPO_BRANCH}.zip"
        else
            echo "${KAAL_REPO}/archive/master.zip"
        fi
    else
        echo "aHR0cHM6Ly9naXRodWIuY29tL2thYWwwNDA4L0tBQUxCT1Q=" | base64 -d
    fi
}


_set_bot () {
    local zippath
    zippath="KAALBOT.zip"
    echo "  Downloading source code ..."
    wget -q $(_get_repolink) -O "$zippath"
    echo "  Unpacking Data ..."
    KAALPATH=$(zipinfo -1 "$zippath" | grep -v "/.");
    unzip -qq "$zippath"
    echo "Done"
    echo "  Cleaning ..."
    rm -rf "$zippath"
    sleep 5
    cd $KAALPATH
    echo "    Starting KAALBOT    "
    echo "
                          ╔═╦═╦══╦══╦══╦══╦══╦═╦══╗
                          ║║║║║╔╗║═╦╩║║╣╔╗║╔╗║║╠╗╔╝
                          
                          ╚╩═╩╩╝╚╩╝─╚══╩╝╚╩══╩═╝╚╝
    "

    python3 ./setup/updater.py ./requirements.txt requirements.txt
    python3 -m userbot
}

_set_bot
