#!/bin/bash


_get_repolink () {
    local regex
    regex='(https?)://github.com/.+/.+'
    if [[ $Kala_REPO == "KalaBot" ]]
    then
        echo "aHR0cHM6Ly9naXRodWIuY29tL2thYWwwNDA4L0tBQUxCT1QvYXJjaGl2ZS9tYWluLnppcA==" | base64 -d
    elif [[ $Kala_REPO == "KalaBot" ]]
    then
        echo "aHR0cHM6Ly9naXRodWIuY29tL2thYWwwNDA4L0tBQUxCT1QvYXJjaGl2ZS9tYWluLnppcA==" | base64 -d
    elif [[ $Kala_REPO =~ $regex ]]
    then
        if [[ $Kala_REPO_BRANCH ]]
        then
            echo "${Kala_REPO}/archive/${Kala_REPO_BRANCH}.zip"
        else
            echo "${Kala_REPO}/archive/master.zip"
        fi
    else
        echo "aHR0cHM6Ly9naXRodWIuY29tL2thYWwwNDA4L0tBQUxCT1QvYXJjaGl2ZS9tYWluLnppcA==" | base64 -d
    fi
}


_set_bot () {
    local zippath
    zippath="KalaBot.zip"
    echo "  Downloading source code ..."
    wget -q $(_get_repolink) -O "$zippath"
    echo "  Unpacking Data ..."
    KalaPATH=$(zipinfo -1 "$zippath" | grep -v "/.");
    unzip -qq "$zippath"
    echo "Done"
    echo "  Cleaning ..."
    rm -rf "$zippath"
    sleep 5
    cd $KalaPATH
    echo "    Starting KalaBot    "
    echo "
    KalaBOT
    "

    python3 ../setup/updater.py ../requirements.txt requirements.txt
    python3 -m userbot
}

_set_bot
